name: punk_messenger
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^3.0.0
  async: ^2.4.2
  auth: ^7.3.2
  cloud_firestore: null
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  flutter_automation: ^1.4.0
  flutter_dotenv: ^3.1.0
  flutter_signin_button: ^1.0.0
  flutter_svg: ^0.17.4
  google_sign_in: ^4.5.9
  modal_progress_hud: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - .env
